#!/usr/bin/env python3

import argparse
import subprocess
import tempfile

parser = argparse.ArgumentParser()
parser.add_argument("file", help="Input file")
parser.add_argument("-o", "--output", help="Output file")
parser.add_argument("-E", "--preprocessor-only",
                    help="Only run the preprocessor", action="store_true")
parser.add_argument("-c", "--object-file-only", help="Only output object file",
                    action="store_true")
args = parser.parse_args()

pp = subprocess.Popen(
    ['java', '-jar', 'pp/target/scala-2.13/parser.jar', args.file],
    stdout=subprocess.PIPE)
cc = subprocess.Popen(['cc/target/debug/c4cc'],
                      stdin=pp.stdout, stdout=subprocess.PIPE)
opt = subprocess.Popen(['opt'], stdin=cc.stdout, stdout=subprocess.PIPE)

obj_file = tempfile.NamedTemporaryFile(delete=False)
ass = subprocess.Popen(['llc', '--filetype=obj'],
                       stdin=opt.stdout, stdout=obj_file)
pp.wait()
cc.wait()
opt.wait()
ass.wait()
obj_file.close()

ln = subprocess.Popen(['clang', obj_file.name, '-o', args.output or 'a.out'])
ln.wait()
