
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package c4.ast;

/** CUP generated class containing symbol constants. */
public class CupSymbols {
  /* terminals */
  public static final int error = 1;
  public static final int PLUS = 3;
  public static final int NUMBER = 4;
  public static final int SEMI = 2;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEMI",
  "PLUS",
  "NUMBER"
  };
}

