
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package c4.ast;

/** CUP generated class containing symbol constants. */
public class CupSymbols {
  /* terminals */
  public static final int QMARK = 77;
  public static final int SHORT = 32;
  public static final int SIGNED = 33;
  public static final int MOD_ASSIGN = 82;
  public static final int GT = 68;
  public static final int SUB_ASSIGN = 84;
  public static final int CONST = 16;
  public static final int B_OR_ASSIGN = 89;
  public static final int INTEGER_LIT = 3;
  public static final int L_AND = 75;
  public static final int LONG_DOUBLE_LIT = 6;
  public static final int GEQ = 70;
  public static final int REGISTER = 30;
  public static final int ENUM = 22;
  public static final int SIZEOF = 34;
  public static final int COMMA = 51;
  public static final int RBRACE = 49;
  public static final int RPAREN = 47;
  public static final int WIDE_CHAR_LIT = 8;
  public static final int DOUBLE = 20;
  public static final int SUB = 60;
  public static final int STRUCT = 36;
  public static final int LBRACE = 48;
  public static final int LPAREN = 46;
  public static final int TILDE = 61;
  public static final int RSHIFT_ASSIGN = 86;
  public static final int FLOAT_LIT = 4;
  public static final int LE = 67;
  public static final int XOR_ASSIGN = 88;
  public static final int DEC = 56;
  public static final int FLOAT = 24;
  public static final int GOTO = 26;
  public static final int EQ = 71;
  public static final int MOD = 64;
  public static final int PTR = 54;
  public static final int B_AND_ASSIGN = 87;
  public static final int L_NOT = 62;
  public static final int ADD_ASSIGN = 83;
  public static final int LONG = 29;
  public static final int B_OR = 74;
  public static final int WHILE = 43;
  public static final int UNION = 39;
  public static final int MUL_ASSIGN = 80;
  public static final int ASSIGN = 79;
  public static final int TYPEDEF_NAME = 11;
  public static final int CHAR = 15;
  public static final int SWITCH = 37;
  public static final int DO = 19;
  public static final int FOR = 25;
  public static final int STAR = 58;
  public static final int VOID = 41;
  public static final int ADD = 59;
  public static final int EXTERN = 23;
  public static final int DIV = 63;
  public static final int RETURN = 31;
  public static final int DOUBLE_LIT = 5;
  public static final int ELSE = 21;
  public static final int BREAK = 13;
  public static final int DOT = 50;
  public static final int INT = 28;
  public static final int EOF = 0;
  public static final int SEMICOLON = 52;
  public static final int STR_LIT = 9;
  public static final int RSBRKT = 45;
  public static final int DEFAULT = 18;
  public static final int INC = 55;
  public static final int LSBRKT = 44;
  public static final int L_OR = 76;
  public static final int error = 1;
  public static final int CONTINUE = 17;
  public static final int IF = 27;
  public static final int UNSIGNED = 40;
  public static final int LSHIFT_ASSIGN = 85;
  public static final int ID = 2;
  public static final int DIV_ASSIGN = 81;
  public static final int COLON = 78;
  public static final int VOLATILE = 42;
  public static final int CASE = 14;
  public static final int CHAR_LIT = 7;
  public static final int RSHIFT = 66;
  public static final int WIDE_STR_LIT = 10;
  public static final int NEQ = 72;
  public static final int ELLIPSIS = 53;
  public static final int STATIC = 35;
  public static final int LSHIFT = 65;
  public static final int TYPEDEF = 38;
  public static final int XOR = 73;
  public static final int AUTO = 12;
  public static final int LEQ = 69;
  public static final int B_AND = 57;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "INTEGER_LIT",
  "FLOAT_LIT",
  "DOUBLE_LIT",
  "LONG_DOUBLE_LIT",
  "CHAR_LIT",
  "WIDE_CHAR_LIT",
  "STR_LIT",
  "WIDE_STR_LIT",
  "TYPEDEF_NAME",
  "AUTO",
  "BREAK",
  "CASE",
  "CHAR",
  "CONST",
  "CONTINUE",
  "DEFAULT",
  "DO",
  "DOUBLE",
  "ELSE",
  "ENUM",
  "EXTERN",
  "FLOAT",
  "FOR",
  "GOTO",
  "IF",
  "INT",
  "LONG",
  "REGISTER",
  "RETURN",
  "SHORT",
  "SIGNED",
  "SIZEOF",
  "STATIC",
  "STRUCT",
  "SWITCH",
  "TYPEDEF",
  "UNION",
  "UNSIGNED",
  "VOID",
  "VOLATILE",
  "WHILE",
  "LSBRKT",
  "RSBRKT",
  "LPAREN",
  "RPAREN",
  "LBRACE",
  "RBRACE",
  "DOT",
  "COMMA",
  "SEMICOLON",
  "ELLIPSIS",
  "PTR",
  "INC",
  "DEC",
  "B_AND",
  "STAR",
  "ADD",
  "SUB",
  "TILDE",
  "L_NOT",
  "DIV",
  "MOD",
  "LSHIFT",
  "RSHIFT",
  "LE",
  "GT",
  "LEQ",
  "GEQ",
  "EQ",
  "NEQ",
  "XOR",
  "B_OR",
  "L_AND",
  "L_OR",
  "QMARK",
  "COLON",
  "ASSIGN",
  "MUL_ASSIGN",
  "DIV_ASSIGN",
  "MOD_ASSIGN",
  "ADD_ASSIGN",
  "SUB_ASSIGN",
  "LSHIFT_ASSIGN",
  "RSHIFT_ASSIGN",
  "B_AND_ASSIGN",
  "XOR_ASSIGN",
  "B_OR_ASSIGN"
  };
}

