[package]
name = "c4cc"
version = "0.1.0"
authors = ["Chenguang Wang <w3cing@gmail.com>"]
edition = "2018"

[features]
default = ["llvm-sys"]

[dependencies]
llvm-sys = { version = "100.0.1", optional = true }
protobuf = "2.18"

[build-dependencies]
protoc-rust = "2.18"
